/*
  Write a program to input a sentence and 
  convert it into upppercase and display
  each word in a seperate line.
  
  EXAMPLE:
  
  Input: India is my country
  Output: 
          INDIA
          IS
          MY
          COUNTRY
 */

import java.util.*;
public class Class_19
{
    public static void main()
    {
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter a sentence: ");
        String str = sc.nextLine(); //Entered a sentence
        str.trim(); //Trimmed the string
        str = str.toUpperCase(); //Converted it to uppercase
        int l = str.length(); //Found the length
        
        for(int i = 0; i < l; i++) //for loop executes till the last index of the entered string
        {
            char ch = str.charAt(i); //finds the character at the specific index generated by the loop
            if(ch == ' ')
            {
                System.out.println(" "); //creats a next line if the character is a space
            }
            else
            {
                System.out.print(ch); //prints the respective characters without going to a next line
            }
        }
    }
}